/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditsIndexRouteImport } from './routes/audits.index'
import { Route as AuditsIdRouteImport } from './routes/audits.$id'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api/uploads.$filename'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIndexRoute = AuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIdRoute = AuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/$filename',
  path: '/$filename',
  getParentRoute: () => ApiUploadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/audits/$id': typeof AuditsIdRoute
  '/audits/': typeof AuditsIndexRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/audits/$id': typeof AuditsIdRoute
  '/audits': typeof AuditsIndexRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/audits/$id': typeof AuditsIdRoute
  '/audits/': typeof AuditsIndexRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/settings'
    | '/api/uploads'
    | '/audits/$id'
    | '/audits/'
    | '/api/uploads/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/settings'
    | '/api/uploads'
    | '/audits/$id'
    | '/audits'
    | '/api/uploads/$filename'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/settings'
    | '/api/uploads'
    | '/audits/$id'
    | '/audits/'
    | '/api/uploads/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  SettingsRoute: typeof SettingsRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  AuditsIdRoute: typeof AuditsIdRoute
  AuditsIndexRoute: typeof AuditsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/': {
      id: '/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$id': {
      id: '/audits/$id'
      path: '/audits/$id'
      fullPath: '/audits/$id'
      preLoaderRoute: typeof AuditsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
  }
}

interface ApiUploadsRouteChildren {
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  SettingsRoute: SettingsRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  AuditsIdRoute: AuditsIdRoute,
  AuditsIndexRoute: AuditsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
