/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditsIndexRouteImport } from './routes/audits.index'
import { Route as AuditsIdRouteImport } from './routes/audits.$id'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIndexRoute = AuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIdRoute = AuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/workshops': typeof WorkshopsRoute
  '/audits/$id': typeof AuditsIdRoute
  '/audits/': typeof AuditsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/workshops': typeof WorkshopsRoute
  '/audits/$id': typeof AuditsIdRoute
  '/audits': typeof AuditsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/workshops': typeof WorkshopsRoute
  '/audits/$id': typeof AuditsIdRoute
  '/audits/': typeof AuditsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/machines'
    | '/settings'
    | '/workshops'
    | '/audits/$id'
    | '/audits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/machines'
    | '/settings'
    | '/workshops'
    | '/audits/$id'
    | '/audits'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/machines'
    | '/settings'
    | '/workshops'
    | '/audits/$id'
    | '/audits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  MachinesRoute: typeof MachinesRoute
  SettingsRoute: typeof SettingsRoute
  WorkshopsRoute: typeof WorkshopsRoute
  AuditsIdRoute: typeof AuditsIdRoute
  AuditsIndexRoute: typeof AuditsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/': {
      id: '/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$id': {
      id: '/audits/$id'
      path: '/audits/$id'
      fullPath: '/audits/$id'
      preLoaderRoute: typeof AuditsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  MachinesRoute: MachinesRoute,
  SettingsRoute: SettingsRoute,
  WorkshopsRoute: WorkshopsRoute,
  AuditsIdRoute: AuditsIdRoute,
  AuditsIndexRoute: AuditsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
